The materials in this section were largely adopted from [Dr. Jason Moore's research group](https://mechmotum.github.io/guide-writing.html#toc-entry-5). 

### Critical thinking

We ask you to write reports/papers/thesis/dissertations in school so that you learn how to write. 
You may not see it yet, but writing is also a key to improving your critical thinking. 
The act of communicating each and every sentence, helps you think out the complexity of the work you are doing. 
If you let AI write for you, you remove a large amount of the thinking you need to be doing to become a researcher or engineer.

AI is a tool that you can use to help you in your work. 
But it should not be used to directly produce any content that we use and publish. 

| Permitted | Non Permitted |
|---------|------|
| Write a paragraph by yourself. | Prompt AI to generate a paragraph and paste it into your writing. |
| Write a paragraph, provide it to AI and ask for adjustments and feedback, manually rewrite the paragraph based on the AI's feedback.   | Write a paragraph, provide it to AI and ask it to improve the paragraph, paste the paragraph from AI into your writing.   |
| Prompt AI to check the grammar in your writing, manually fix grammar that is suggested by AI.   | Pass your writing to AI and prompt it to fix the grammar and spelling, paste the result into your writing.   |

: {tbl-colwidths="[50,50]"}


### Statement On AI Use

If you make use of AI tools that can essentially generate texts, images, or code for you, you must make a statement in your document explaining how you used such tools. 
You should also be cautious when using such AI tools because the copyright of the AI content is ambiguous. 
The AI content is a derivative of other people's (possibly copyrighted) work, and you do not want to laden your writing with possible copyright infringements. 
You are required to make a statement on AI use, for example:

> During the preparation of this work the author(s) used Grammarly to improve the grammar in the writing.
> After using this tool/service, the author(s) manually reviewed and edited the content as needed. 
> No contents, including texts, images, and source code, were directly generated by AI. 